### ISSUE TITLE
abbreviations

### ISSUE THREAD

**Issue by electrovir** [thesocialcontract/Aji#5]
Personally I avoid using abbreviations (`str`), even for basic types like this. Just makes it more clear imo. (I recognize this isn't typical and perhaps even against language conventions. Just my personal preference.)

https://github.com/thesocialcontract/Aji/blob/b65c0b520a392bf35032fe6a56fcd7cac1681d80/app/game_sgf_io.py#L12

**Comment by electrovir** [comment]
ooo that GitHub code line reference thing is sweet!

**Comment by thesocialcontract** [comment]
I def agree except I think it's fine for basic types.  Things like num or str are well known enough that it's clear.  Python agrees :)

```type("example")``` returns ```<class 'str'>```
