### ISSUE TITLE
string interpolation

### ISSUE THREAD

**Issue by electrovir** [thesocialcontract/Aji#7]
If string interpolation works this well (not familiar with Python enough to be sure), the previous lines here can also be included here, rather than using `+=` to build it up.

https://github.com/thesocialcontract/Aji/blob/b65c0b520a392bf35032fe6a56fcd7cac1681d80/app/game.py#L98

**Comment by thesocialcontract** [comment]
Yeah idk what I was thinking, that's a weird way to build a string.  I'll refactor.
