### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by electrovir** [thesocialcontract/Aji#8]
camelCase inside surrounded by snake_case (personally I prefer camelCase but consistency wins over preference).

https://github.com/thesocialcontract/Aji/blob/b65c0b520a392bf35032fe6a56fcd7cac1681d80/tests/test_game.py#L10

**Comment by thesocialcontract** [comment]
This is special syntax per python's unittest module (underscore naming is python convention, so I suspect they chose camelCase because it was unlikely to be collided with)
