### ISSUE TITLE
util file

### ISSUE THREAD

**Issue by electrovir** [thesocialcontract/Aji#9]
I usually create a `util` folder rather than a single file. Scales better and allows more granular files.

https://github.com/thesocialcontract/Aji/blob/b65c0b520a392bf35032fe6a56fcd7cac1681d80/tests/fixtures/utils.py#L12

**Comment by thesocialcontract** [comment]
Yeah that's fair.  I want to avoid having a large testing utils suite--if there are a lot, I likely have a problem with my testing strategy or my architecture.
